services:
  - type: web
    name: face-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn face_detection.api.main:app --host 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FACE_DETECTION_MODEL
        value: VGG-Face
      - key: FACE_DETECTION_BACKEND
        value: opencv
      - key: FACE_DETECTION_METRIC
        value: cosine
      - key: FACE_ANALYSIS_ACTIONS
        value: '["age", "gender", "emotion"]'
      - key: TF_CPP_MIN_LOG_LEVEL
        value: '2'  # Suppress TensorFlow warnings
      - key: TF_ENABLE_ONEDNN_OPTS
        value: '1'  # Enable oneDNN optimizations
      - key: TF_XLA_FLAGS
        value: '--tf_xla_enable_xla_devices'  # Enable XLA optimizations
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: 'true'
      - key: KERAS_BACKEND
        value: 'tensorflow' 